### ISSUE TITLE
Unable to save fragment on fresh install

### ISSUE THREAD

**Issue by theSdev** [markvincze/vscode-codeFragments#4]
Hi.
On fresh install, when I attempted to save a code fragment I got this error message:

> command 'codeFragments.saveSelectedCodeFragment' not found

Then I inserted the "example" fragment and that seemed to initialize something as the problem was solved.
Reinstall gave me the same behavior.

**Comment by markvincze** [comment]
@theSdev,

I managed to reproduce (kinda): if I try to create a fragment without ever opening the Explorer bar, then it simply doesn't work, so the fragment is not saved.  
But I don't get any error message, so it might be that this is a different bug.

Where did you see the error message appear, in a usual VSCode notification?

**Comment by markvincze** [comment]
@theSdev,

Ok, found it. Interesting, if I try to reproduce by right clicking and selecting the command from the context menu, then I get the behavior I described above, and if I do it from the Command Palette, then I get the error you mentioned.  
I'll deliver a fix.

**Comment by markvincze** [comment]
Released a fix with 1.1.1.
