### ISSUE TITLE
Ask for a name on fragment saving

### ISSUE THREAD

**Issue by theSdev** [markvincze/vscode-codeFragments#5]
Hi.
Default fragment names don't seem useful to me. I think asking for a name on save is a better approach rather than manually selecting and renaming fragments. Default names could be used if the user leaves the name empty.
Thanks.

**Comment by markvincze** [comment]
Hi @theSdev,

Thanks for submitting this idea. I implement it now in version 1.2.0.  
It's turned off by default, you have to turn it on with the `codeFragments.askForNameOnCreate` setting.
